---
- hosts: 172.31.39.239
  become: yes
  tasks:
  - name: execute linux command
    command:  hostname -f
    register: myresult
  

  - name: i want to display my first task result
    debug:
      msg: "{{myresult}}"

  - name: install
    apt:
      name: git 
      state: present

  - name: install tree
    apt:
      name: tree
      state: present 
    when: myresult.stderr --""
