---
- hosts: 172.31.39.239
  become: yes
  vars:
     myvar01: git 
     myvar02: tree
     myvar03: wget
  tasks: 
  - name: i want to display myvar02
    debug:
       msg: "{{myvars02}}" 
       
       

