---
- hosts: all
  become: yes
  tasks:
  - name: i want install webserve on ubuntu ansible nodes
    apt:
      name: apache2
      state: present

  - name:  i want to start webserve on ubuntu ansible nodes
    service:
       name: apache2
       state: restarted
       