---
- hosts: myWebServers
  become: yes
  tasks:
  - name: i want install webserve on ubuntu ansible nodes
    apt:
      name: "{{webpackonubuntu}}"
      state: present
    when: ansible_os_family =="debian"

  - name:  i want to start webserve on ubuntu ansible nodes
    service:
       name: "{{webpackonubuntu}}"
       state: restarted
    when: ansible_os_family =="debian"

  - name: i want to webserver on RedHat ansible nodes
    yum:
      name: "{{webpackonredhar}}"
      state: present
    when: ansible_os_family =="RedHat"

  - name: i want to startwebserver on RedHat ansible nodes
    service:
       name: "{{webpackonredhar}}"
       state: started
    when: ansible_os_family =="RedHat"
       
